AWSTemplateFormatVersion: '2010-09-09'
Description: |
    This CloudFormation template allows for the creation of an IAM role with specific permissions, with the role name being provided as a parameter. The output provides the ARN of the created IAM role.

Parameters:
  RoleName:
    Type: String
    Description: Name for the IAM Role
  IncludeEC2StartStopPermissions:
    Type: String
    Description: Include EC2 start/stop permissions (yes/no)
    AllowedValues: ['yes', 'no']
    Default: "no"
  IncludeS3DuplicateObjectsPermission:
    Type: String
    Description: Include S3 ListBucket permission (yes/no)
    AllowedValues: ['yes', 'no']
    Default: "no"

Conditions:
  IncludeEC2StartStopPermissionsCondition: !Equals [!Ref IncludeEC2StartStopPermissions, "yes"]
  IncludeS3DuplicateObjectsPermissionCondition: !Equals [!Ref IncludeS3DuplicateObjectsPermission, "yes"]

Resources:
  DigiusherIAMRole:
    Type: AWS::IAM::Role
    Description: |
      Creates an IAM role by allowing a trust relationship with Digiusher's Account ID and providing specific permissions for accessing AWS services.
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              AWS: !Sub "arn:aws:iam::058264546051:root"
            Action: sts:AssumeRole
      RoleName: !Ref RoleName
      Policies:
        - PolicyName: DigiUsherRolePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Sid: DigiUsherRecommendationsPermissions
                Effect: Allow
                Action:
                  - cloudwatch:GetMetricStatistics
                  - cur:DescribeReportDefinitions
                  - ec2:Describe*
                  - iam:GetAccessKeyLastUsed
                  - iam:GetLoginProfckoile
                  - iam:ListAccessKeys
                  - iam:ListUsers
                  - rds:DescribeDBInstances
                  - s3:GetBucketAcl
                  - s3:GetBucketLocation
                  - s3:GetBucketPolicyStatus
                  - s3:GetBucketPublicAccessBlock
                  - s3:GetBucketTagging
                  - s3:ListAllMyBuckets
                  - ce:GetReservationPurchaseRecommendation
                  - ce:GetRightsizingRecommendation
                  - ce:GetSavingsPlansPurchaseRecommendation
                Resource: "*"
        - !If
          - IncludeEC2StartStopPermissionsCondition
          - PolicyName: DigiUsherEC2StartStopPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Sid: EC2StartStopPermissions
                  Effect: Allow
                  Action:
                    - ec2:StartInstances
                    - ec2:StopInstances
                  Resource: "*"
          - !Ref "AWS::NoValue"
        - !If
          - IncludeS3DuplicateObjectsPermissionCondition
          - PolicyName: DigiUsherS3DuplicateObjectsPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Sid: S3DuplicateObjectsPermission
                  Effect: Allow
                  Action:
                    - s3:ListBucket
                  Resource: "*"
          - !Ref "AWS::NoValue"

Outputs:
  IAMRoleArn:
    Description: Role ARN Value
    Value: !GetAtt DigiusherIAMRole.Arn
